# Generated by Django 5.1.4 on 2025-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('public_key', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('encrypted_services', models.BinaryField(blank=True, editable=True, null=True)),
            ],
            options={
                'verbose_name': 'User Services',
                'verbose_name_plural': 'User Services',
            },
        ),
    ]
