volumes:
  pg_data_production:
  static_volume:

services:

  db:
    image: postgres:17.2
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: mvlbulankin/passcryptum_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # frontend:
  #   image: mvlbulankin/passcryptum_frontend
  #   env_file: .env
  #   command: cp -r /app/dist/. /frontend_static/
  #   volumes:
  #     - static_volume:/frontend_static
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  gateway:
    image: mvlbulankin/passcryptum_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"