# Generated by Django 5.1.4 on 2025-02-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin", models.CharField(max_length=256)),
                ("protector", models.CharField(max_length=32)),
                ("entropy", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Secret",
                "verbose_name_plural": "Profile Secrets",
            },
        ),
    ]
