# Generated by Django 5.1.4 on 2025-02-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
        ("profiles", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileSecret",
            new_name="Credential",
        ),
        migrations.AlterModelOptions(
            name="credential",
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
            },
        ),
    ]
