# Generated by Django 5.1.4 on 2025-03-06 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_rename_profilesecret_credential_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
