# Generated by Django 5.1.4 on 2025-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0003_credential_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="protector",
            field=models.CharField(max_length=256),
        ),
    ]
