# Generated by Django 5.1.4 on 2025-01-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "public_key",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("services", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
